### ISSUE TITLE
Include controller is failing if open JMX files in JMeter GUI

### ISSUE THREAD

**Issue by bobmeliev** [jmeter-templates/wordpress#1]
Both JMX files single-user.jmx and loadtest.jmx are failing while reading modules. 

jmeter.control.IncludeController: loadIncludedElements -Attempting to read it from: /home/jmeter/apache-jmeter-2.12/bin/modules/core/Homepage.jmx

**Comment by shmuel-krakower** [comment]
Hi @bobmeliev - the way you should use this framework is that you need to define `%JMETER_HOME%` evnironment variable to point to your JMeter installation.
As I see you are using linux - I guess you should create a bash script which is equivalent to the existing bat(ch) files. Something like:
`%JMETER_PATH%/bin/jmeter.sh -p single-user-dev.properties -t single-user.jmx`

This is noted also in: https://github.com/jmeter-templates/wordpress#usage
