### ISSUE TITLE
View Page Post etc cannot pass test

### ISSUE THREAD

**Issue by GuuBu** [jmeter-templates/wordpress#2]
Hi,
Thanks a lot for sharing the test codes here. I'm currently try to run the test against with both default settings and my wordpress websites, and removed some part of the test to check how it runs. I find all the post related test cannot pass. 
E.g.  step "Anonymous View Blog Post"  gives error:java.net.URISyntaxException: Illegal character in path at index 23: http://wordpress.org/${blog_post_relative_path}&#

May I ask is that because I misconfigure something for the test or website? Thanks a lot.

Best Regards,
Qianqian

**Comment by GuuBu** [comment]
And it seems for me that the test is targeted at wordpress.org official website. May I ask is there any sample data I can pre-install in order to make the test work for my own site? Or how should I modify the subpath and other configuration? 

Thanks & Best Regards,
Qianqian

**Comment by GuuBu** [comment]
And may I have a ask that do you mean other  test template against WordPress website that is well known and used?  Thanks a lot.  I'm new to web app and web test world, and want to find some standard way to do functionality  and stress test for Wordpress.

Thanks & Best Regards,
Qianqian

**Comment by GuuBu** [comment]
And also I find that Anonymous Homepage test and some other tests can still pass when I changed the setting to my own website, but didn't provide the correct user name. May I know what I'm missing? Dose the Login.jmx got ran for these tests?

Thanks & Best Regards,
Qianqian Bu

**Comment by shmuel-krakower** [comment]
Hi Qianqian,
Sorry it took so much time to reply.

I guess your questions are rather basic to jmeter and once you get to know how jmeter works you'll get to figure out how to use this template better. Feel free to remove some parameters and put hardcoded urls/parameters to make it work and debug.

If you need basic jmeter training, you may find some examples online.
You should also join the apache jmeter users list.

**Comment by GuuBu** [comment]
Hi Shmuel,

Thanks a lot for your reply. I have got some learning for JMeter, and know better about how Jmeter works now. Thanks for taking time to reply this.

Best Regards,
Qianqian Bu
